# Generated by Django 4.2.4 on 2023-08-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0002_customerdb_salesdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdb',
            name='Price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
