# Generated by Django 4.2.4 on 2023-08-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0006_alter_productdb_price_alter_salesdb_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdb',
            name='Price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
