# Generated by Django 4.2.4 on 2023-08-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0007_alter_salesdb_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdb',
            name='Price',
        ),
        migrations.AddField(
            model_name='salesdb',
            name='Total',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
