# Generated by Django 4.2.4 on 2023-08-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0009_alter_salesdb_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdb',
            name='Price',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productdb',
            name='Price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
