# Generated by Django 4.2.4 on 2023-08-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0011_billdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='pricechart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fat', models.FloatField(blank=True, max_length=100, null=True)),
                ('snf', models.FloatField(blank=True, max_length=100, null=True)),
                ('rate', models.FloatField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
