# Generated by Django 4.2.4 on 2023-08-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0012_pricechart'),
    ]

    operations = [
        migrations.CreateModel(
            name='milkdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cardno', models.IntegerField(blank=True, null=True)),
                ('Farmer', models.CharField(blank=True, max_length=1000, null=True)),
                ('Milkmng', models.FloatField(blank=True, null=True)),
                ('Milkevg', models.FloatField(blank=True, null=True)),
                ('Total', models.FloatField(blank=True, null=True)),
                ('FAT', models.FloatField(blank=True, null=True)),
                ('SNF', models.FloatField(blank=True, null=True)),
                ('Rate', models.FloatField(blank=True, null=True)),
                ('Totalrate', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='billdb',
            name='Total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricechart',
            name='fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricechart',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricechart',
            name='snf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesdb',
            name='Price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesdb',
            name='Total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
