# Generated by Django 4.2.4 on 2023-08-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0013_milkdb_alter_billdb_total_alter_pricechart_fat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkdb',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
    ]
