# Generated by Django 4.2.4 on 2023-08-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0016_remove_milkdb_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoicedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True)),
                ('Customer', models.CharField(blank=True, max_length=100, null=True)),
                ('Total', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
