# Generated by Django 4.2.4 on 2023-08-04 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerdb',
            name='CardNo',
        ),
    ]
