# Generated by Django 4.2.4 on 2023-08-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_registerdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerdb',
            name='id',
        ),
        migrations.AddField(
            model_name='farmerdb',
            name='Cardno',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
