# Generated by Django 4.2.4 on 2023-08-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_remove_farmerdb_id_farmerdb_cardno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerdb',
            name='Cardno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
