# Generated by Django 4.2.4 on 2023-08-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_farmerdb_id_alter_farmerdb_cardno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerdb',
            name='Cardno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
