# Generated by Django 4.2.4 on 2023-08-24 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_alter_farmerdb_cardno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerdb',
            name='Cardno',
        ),
    ]
