# Generated by Django 4.2.4 on 2023-08-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_remove_farmerdb_cardno'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerdb',
            name='Cardno',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
