# Generated by Django 4.2.4 on 2023-08-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_farmersdb_delete_farmerdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmerdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=1000, null=True)),
                ('Dateofbirth', models.CharField(blank=True, max_length=1000, null=True)),
                ('Gender', models.CharField(blank=True, max_length=10, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='employee')),
            ],
        ),
        migrations.DeleteModel(
            name='farmersDB',
        ),
    ]
