# Generated by Django 4.2.4 on 2023-08-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_farmerdb_cardno'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='image')),
            ],
        ),
    ]
