# Generated by Django 4.2.4 on 2023-09-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_orderdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdb',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
    ]
