# Generated by Django 4.2.4 on 2023-09-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0020_messagedb_remove_orderdb_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagedb',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
    ]
