# Generated by Django 4.2.4 on 2023-09-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0021_messagedb_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdb',
            name='Status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
