# Generated by Django 4.2.4 on 2023-09-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0022_orderdb_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdb',
            name='Status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
