# Generated by Django 4.2.4 on 2023-09-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0023_alter_orderdb_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='Price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
